PostgresqlEntityDemo/Models/College.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgresqlEntityDemo.Models
{
    public class College
    { 

        [DisplayName("ID")]
        public int CollegeId { get; set; }
        public string? Location { get; set; }
        [Column(Order = 2)]
        public string?  Name { get; set; }

    }
}

PostgresqlEntityDemo/Models/ErrorViewModel.cs
namespace PostgresqlEntityDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PostgresqlEntityDemo/Models/LastNameAttribute.cs
namespace PostgresqlEntityDemo.Models
{
    internal class LastNameAttribute : Attribute
    {
    }
}

PostgresqlEntityDemo/Models/Students.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgresqlEntityDemo.Models
{
    public class Students
    {
        [Key]
       
        public int Id { get; set; }
        [Required]
        
        public string?  FirstName { get; set; }
       
        public string?  LastName { get; set; }
        public int RollNumber { get; set; }

    }
}

PostgresqlEntityDemo/Controllers/CollegesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PostgresqlEntityDemo.Data;
using PostgresqlEntityDemo.Models;
using System.Linq;

namespace PostgresqlEntityDemo.Controllers
{
    public class CollegesController : Controller
    {
        ApplicationDbContext _applicationDbContext;
        public CollegesController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
        // GET: HomeController1
        public ActionResult Index()
        {
            IEnumerable<College> CollegeList = _applicationDbContext.Colleges.OrderByDescending(x => x.CollegeId);
            return View(CollegeList);
        }

        // GET: HomeController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(College obj)
        {
            try
            {
                    _applicationDbContext.Colleges.Add(obj);
                    _applicationDbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));  
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Edit/5
        public ActionResult Edit(int id)
        {
            if(id == 0 )
            {
                return NotFound();  
            }
            var collegeFormDb = _applicationDbContext.Colleges.Find(id);
            if(collegeFormDb == null)
            {
                return NotFound();
            }

            return View(collegeFormDb);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, College obj)
        {
            try
            {
                _applicationDbContext.Colleges.Update(obj);
                _applicationDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Delete/5
        public ActionResult Delete(int id)
        {
            if(id ==0 )
            {
                return NotFound();
            }
            var collegeDeleteDb = _applicationDbContext.Colleges.Find(id);  
            if(collegeDeleteDb == null) 
            { return NotFound(); }
            _applicationDbContext.Remove(collegeDeleteDb); 
            _applicationDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

       
    }
}

PostgresqlEntityDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PostgresqlEntityDemo.Models;
using System.Diagnostics;

namespace PostgresqlEntityDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PostgresqlEntityDemo/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using PostgresqlEntityDemo.Data;
using PostgresqlEntityDemo.Models;
using System.Collections.Generic;
using System.Linq;

namespace PostgresqlEntityDemo.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public StudentsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
           
            IEnumerable<Students> objStudentsList = _db.Students.OrderByDescending(x => x.Id);
            return View(objStudentsList);
        }
        //get
        public IActionResult Create()
        {
            return View();
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create(Students obj)
        {
            
            if (ModelState.IsValid) {

                _db.Students.Add(obj);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //get
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var studentFormDb = _db.Students.Find(id);
            if(studentFormDb == null)
            {
                return NotFound();
            }

            return View(studentFormDb);
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Students obj)
        {

            if (ModelState.IsValid)
            {
                
                _db.Students.Update(obj);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get//delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var studentFormDb = _db.Students.Find(id);
            if (studentFormDb == null)
            {
                return NotFound();
            }
            _db.Students.Remove(studentFormDb);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
       
    }
}

PostgresqlEntityDemo/Views/Colleges/Create.cshtml
@model PostgresqlEntityDemo.Models.College

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>College</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PostgresqlEntityDemo/Views/Colleges/Edit.cshtml
@model PostgresqlEntityDemo.Models.College

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>College</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CollegeId" />
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PostgresqlEntityDemo/Views/Colleges/Index.cshtml
@model IEnumerable<PostgresqlEntityDemo.Models.College>

@{
    ViewData["Title"] = "Index";
}




<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">College List</h2>
        </div>
         <div class="col-6 text-end" >
  
           <a asp-controller="Colleges" asp-action="Create"  class=" btn btn-primary"><i class="bi bi-plus-square"></i>Add College</a>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
             
             <th>
                @Html.DisplayNameFor(model => model.CollegeId)
            </th>
          
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                <p3>Edit</p3>
            </th>
            <th>
                 <p3>Details</p3>
            </th>
            <th>
                 <p3>Delete</p3>
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.CollegeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            
            <td>
                <a class=" btn btn-secondary" asp-action="Edit" asp-route-id="@item.CollegeId"><i class="bi bi-pencil-square"></i>Edit</a> 
                 
                
            </td>
            <td>
                <a class=" btn btn-info" asp-action="Details" asp-route-id="@item.CollegeId"><i class="bi bi-info-circle"></i>Details</a>
            </td>
            <td>
                <a class=" btn btn-danger" asp-action="Delete" asp-route-id="@item.CollegeId"><i class="bi bi-trash3"></i>Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PostgresqlEntityDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PostgresqlEntityDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PostgresqlEntityDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PostgresqlEntityDemo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Students" asp-action="Index"><h1 class="text-primary">StudyDemo</h1></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">StudentsList</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colleges" asp-action="Index">CollegesList</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PostgresqlEntityDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PostgresqlEntityDemo/Views/Students/Create.cshtml
@model Students




<form method="post">
    <div class=" border p-3 mt-4">
        <div class="row pb-3 mt-4">
            <h2 class="text-primary">Add Student</h2>
            <hr />
        
    </div>
    <div class="mb-3">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>

    </div>
    <div class="mb-3">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
     <div class="mb-3">
        <label >Roll Number</label>
        <input asp-for="RollNumber" class="form-control" />
        <span asp-validation-for="RollNumber" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary" style="width:150px">Add Student</button>
    <a asp-controller="Students" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

PostgresqlEntityDemo/Views/Students/Edit.cshtml
@model Students

<form method="post">
    <div class=" border p-3 mt-4">
        <div class="row pb-3 mt-4">
            <h2 class="text-primary">Edit Student</h2>
            <hr />
        
    </div>
    <div class="mb-3">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>

    </div>
    <div class="mb-3">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
     <div class="mb-3">
        <label >Roll Number</label>
        <input asp-for="RollNumber" class="form-control" />
        <span asp-validation-for="RollNumber" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary" style="width:150px" asp-controller="Students" asp-action="Edit" asp-route-data="@Model.Id">Edit Student</button>
    <a asp-controller="Students" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

PostgresqlEntityDemo/Views/Students/Index.cshtml
@model IEnumerable<PostgresqlEntityDemo.Models.Students>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Students List</h2>
        </div>
         <div class="col-6 text-end" >
           <a asp-controller="Students" asp-action="Create" class="btn btn-primary"> <i class="bi bi-plus-square"></i> Add Student</a>
        </div>
    </div>
</div>


<div>
     <table class="table table-striped table-hover">
   <thead>
    <tr>
      <th scope="col">Index</th>
      <th scope="col">FirstName</th>
      <th scope="col">LastName</th>
      <th scope="col">RollNumber</th>
      <th scope="col">Edit</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
    
      @foreach(var Item in Model)
      {
    <tr>
      <th scope="row">@Item.Id</th>
      <td>@Item.FirstName</td>
      <td>@Item.LastName</td>
      <td>@Item.RollNumber</td>
      <td><a class="btn btn-secondary" asp-controller="Students" asp-action="Edit" asp-route-id="@Item.Id" ><i class="bi bi-pencil-square"></i>Edit</a>  </td>
      <td><a class="btn btn-danger" asp-controller="Students" asp-action="Delete" asp-route-id="@Item.Id"><i class="bi bi-trash"></i>delete</a></td>

    </tr>
    }
   
  </tbody>
</table>
</div>
   